### ISSUE TITLE
Fixed-width printing

### ISSUE THREAD

**Issue by bestouff** [meh/rust-hwaddr#3]
Hi,

Would it be possible to have fixed-width printing, i.e. display `00:41:D0:24:00:0B` instead of (currently) `0:41:D0:24:0:B` ?

Cheers

**Comment by meh** [comment]
Fixed on master.

**Comment by bestouff** [comment]
Thanks !
Would it be possible to make a release ?

**Comment by meh** [comment]
Yeah, already published :)

**Comment by bestouff** [comment]
Oh perfect :+1:
