### ISSUE TITLE
Update reqwest version, fails to build on systems with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by sharksforarms** [meh/rust-hwaddr#6]
Would it be possible to update the dependencies to reqwest 0.9 ?

https://github.com/seanmonstar/reqwest/issues/345
https://github.com/rust-lang-nursery/rustup.rs/issues/1518

**Comment by meh** [comment]
Published a new version.

**Comment by sharksforarms** [comment]
awesome thanks
